require 'stattleship'
require 'slack-ruby-bot'

require 'slack-glickman/data/cache'
require 'slack-glickman/stattleship/snackable'
require 'slack-glickman/app'

require 'slack-glickman/commands/base_command'
require 'slack-glickman/commands/colors'
require 'slack-glickman/commands/injuries'
require 'slack-glickman/commands/feats'
require 'slack-glickman/commands/frivolities'
require 'slack-glickman/commands/game_logs'
require 'slack-glickman/commands/help'
require 'slack-glickman/commands/players'
require 'slack-glickman/commands/results'
require 'slack-glickman/commands/schedules'
require 'slack-glickman/commands/scoreboard'
require 'slack-glickman/commands/stat_leaders'
require 'slack-glickman/commands/teamoji'
require 'slack-glickman/commands/top_stats'
require 'slack-glickman/commands/tips'
require 'slack-glickman/commands/unknown'
require 'slack-glickman/commands/venues'
require 'slack-glickman/commands/videos'
